/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CashierController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Cashier;

/**
 *
 * @author Galur Arasy L
 */
public class Cashiers extends javax.swing.JFrame {

    static final String[] headers = {"ID", "Name", "Username", "Password", "Age", "Salary", "Years Experienced", "Transaction Handled"};
    static DefaultTableModel m = new DefaultTableModel(headers, 0);
    static ArrayList<Cashier> sourceData;

    /**
     * Creates new form Employee
     *
     * @throws java.sql.SQLException
     */
    public Cashiers() throws SQLException {
        initComponents();
        cashierTable.setModel(m);
        sourceData = CashierController.get();
        while (m.getRowCount() > 0) {
            m.removeRow(0);
        }
        for (Cashier c : sourceData) {
            String[] rowData = {
                Integer.toString(c.getId_employee()),
                c.getName(),
                c.getUsername(),
                c.getPassword(),
                Integer.toString(c.getAge()),
                Float.toString(c.getSalary()),
                Integer.toString(c.getYears_experienced()),
                Integer.toString(c.getTransaction_handled())
            };
            m.addRow(rowData);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cashierTable = new javax.swing.JTable();
        newCashier = new javax.swing.JButton();
        eliminate = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Employees");

        cashierTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cashierTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cashierTableFocusLost(evt);
            }
        });
        cashierTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cashierTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(cashierTable);

        newCashier.setText("New Cashier");
        newCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCashierActionPerformed(evt);
            }
        });

        eliminate.setText("Eliminate");
        eliminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminateActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eliminate)
                        .addGap(18, 18, 18)
                        .addComponent(newCashier)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCashier)
                    .addComponent(eliminate))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void cashierTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cashierTableFocusLost
    }//GEN-LAST:event_cashierTableFocusLost

    private void cashierTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cashierTableInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cashierTableInputMethodTextChanged

    private void newCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCashierActionPerformed
        this.dispose();
        new CashierAdd().setVisible(true);
    }//GEN-LAST:event_newCashierActionPerformed

    private void eliminateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminateActionPerformed
        try {
            int selectedRow = cashierTable.getSelectedRow();
            CashierController.delete(sourceData.get(selectedRow).getId_employee());
            sourceData = CashierController.get();
            while (m.getRowCount() > 0) {
                m.removeRow(0);
            }
            for (Cashier c : sourceData) {
                String[] rowData = {
                    Integer.toString(c.getId_employee()),
                    c.getName(),
                    c.getUsername(),
                    c.getPassword(),
                    Integer.toString(c.getAge()),
                    Float.toString(c.getSalary()),
                    Integer.toString(c.getYears_experienced()),
                    Integer.toString(c.getTransaction_handled())
                };
                m.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cashiers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_eliminateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashiers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Cashiers().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Cashiers.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cashierTable;
    private javax.swing.JButton eliminate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JButton newCashier;
    // End of variables declaration//GEN-END:variables
}
